---
name: Create Release

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: version to release, e.g. v1.5.13
        required: true
        default: v0.1.0

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        id: setup-go
        with:
          go-version-file: go.mod

#      - name: Download Go modules
#        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
#        run: go mod download

      - name: Login to Docker
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Publish Artifacts
        shell: bash
        env:
          DOCKER_BUILD_ARGS: >-
            --push
        run: make docker.build

#      - name: Generate artifact attestation
#        if: github.event_name != 'pull_request'
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          subject-digest: ${{ steps.build.outputs.digest }}
#          push-to-registry: true
